# Generated by Django 5.0.9 on 2026-05-20 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'actores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color')),
                ('icono', models.CharField(default='bi-tag', max_length=50, verbose_name='Icono')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Método de pago')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'metodos_pago',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (COP)')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='sistema.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='sistema.actor')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sistema.metodopago')),
            ],
            options={
                'db_table': 'gastos',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
